defmodule OpenTrack.Food.FeedTest do
  use OpenTrack.DataCase

  import OpenTrack.Fixtures
  import OpenTrack.AnalysisFixtures

  alias Ecto.Adapters.SQL
  alias OpenTrack.{Accounts, Food}

  test "the feed is actor-scoped, newest first, and responds to unfollows" do
    viewer = user()
    first_followed_user = user()
    second_followed_user = user()
    stranger = user()
    file = upload()
    Accounts.follow_user!(first_followed_user.id, actor: viewer)
    Accounts.follow_user!(second_followed_user.id, actor: viewer)
    # An incoming follow must not populate the viewer's feed.
    Accounts.follow_user!(viewer.id, actor: stranger)

    older = create_unanalyzed_photo(first_followed_user, file)
    own = create_unanalyzed_photo(viewer, file)
    unrelated = create_unanalyzed_photo(stranger, file)
    newer = create_unanalyzed_photo(second_followed_user, file)

    page =
      Food.list_followed_users_photos!(
        actor: viewer,
        page: [limit: 12],
        load: [:image_url, user: [:avatar_url]]
      )

    assert Enum.map(page.results, & &1.id) == [newer.id, older.id]
    refute Enum.any?(page.results, &(&1.id in [own.id, unrelated.id]))
    assert hd(page.results).user.nickname == second_followed_user.nickname
    assert is_binary(hd(page.results).image_url)
    refute hd(page.results).user.email == second_followed_user.email
    refute hd(page.results).user.hashed_password == second_followed_user.hashed_password

    assert Food.list_followed_users_photos!(actor: second_followed_user, page: [limit: 12]).results ==
             []

    follow = Accounts.get_follow!(first_followed_user.id, actor: viewer)
    Accounts.unfollow_user!(follow.id, actor: viewer)

    assert Enum.map(
             Food.list_followed_users_photos!(actor: viewer, page: [limit: 12]).results,
             & &1.id
           ) == [
             newer.id
           ]

    assert {:error, _} = Food.delete_food_photo(newer.id, actor: viewer)
    assert Food.get_food_photo!(newer.id, actor: second_followed_user)
  end

  test "following Ana does not include people Ana follows or duplicate her posts" do
    viewer = user()
    ana = user()
    bob = user()
    other_follower = user()
    file = upload()

    Accounts.follow_user!(ana.id, actor: viewer)
    Accounts.follow_user!(bob.id, actor: ana)
    Accounts.follow_user!(ana.id, actor: other_follower)
    Accounts.follow_user!(viewer.id, actor: bob)

    ana_photo = create_unanalyzed_photo(ana, file)
    bob_photo = create_unanalyzed_photo(bob, file)
    create_unanalyzed_photo(viewer, file)
    create_unanalyzed_photo(other_follower, file)

    page = Food.list_followed_users_photos!(actor: viewer, page: [limit: 12, count: true])
    assert Enum.map(page.results, & &1.id) == [ana_photo.id]
    assert page.count == 1

    # Each actor's outgoing connections, not the uploader's following list, decide
    # which users' photos are included.
    page = Food.list_followed_users_photos!(actor: ana, page: [limit: 12])
    assert Enum.map(page.results, & &1.id) == [bob_photo.id]
  end

  test "the feed joins follows in one query and uses indexed photo lookups" do
    viewer = user()
    followed_user = user()
    Accounts.follow_user!(followed_user.id, actor: viewer)
    photo = create_unanalyzed_photo(followed_user)
    ref = make_ref()
    handler = {__MODULE__, ref}

    :ok =
      :telemetry.attach(
        handler,
        [:open_track, :repo, :query],
        &__MODULE__.record_query/4,
        {self(), ref}
      )

    try do
      page = Food.list_followed_users_photos!(actor: viewer, page: [limit: 12])
      assert Enum.map(page.results, & &1.id) == [photo.id]
      assert_receive {^ref, sql, params}
      refute_receive {^ref, _, _}

      assert sql =~ "INNER JOIN"
      assert sql =~ ~s(FROM "follows")
      refute sql =~ ~s(FROM "users")
      refute String.downcase(sql) =~ "exists("

      # Diagnostic SQL only: the application query above is generated by Ash.
      # Verify the current SQLite plan starts with follows, not a photo scan.
      plan = SQL.query!(Repo, "EXPLAIN QUERY PLAN " <> sql, params)
      details = Enum.map(plan.rows, &List.last/1)
      assert hd(details) =~ "follows_unique_follow_index"

      assert Enum.any?(details, fn detail ->
               detail =~ "SEARCH" and
                 detail =~ "food_photos_user_id_inserted_at_index (user_id=?)"
             end)

      refute Enum.any?(details, &String.contains?(&1, "CORRELATED"))
    after
      :telemetry.detach(handler)
    end
  end

  def record_query(_event, _measurements, metadata, {pid, ref}) do
    send(pid, {ref, metadata.query, metadata.params})
  end

  test "loading a photo's user exposes public identity without granting account access" do
    viewer = user()
    followed_user = user()
    Accounts.follow_user!(followed_user.id, actor: viewer)
    create_unanalyzed_photo(followed_user)

    page =
      Food.list_followed_users_photos!(
        actor: viewer,
        page: [limit: 12],
        load: [user: [:nickname, :email, :hashed_password]]
      )

    assert [photo] = page.results
    assert photo.user.id == photo.user_id
    assert photo.user.nickname == followed_user.nickname
    assert %Ash.ForbiddenField{} = photo.user.email
    assert %Ash.ForbiddenField{} = photo.user.hashed_password

    assert {:error, _} = Accounts.get_user_by_id(followed_user.id, actor: viewer)
    account = Accounts.get_user_by_id!(followed_user.id, actor: followed_user)
    assert account.email == followed_user.email
    assert account.hashed_password == followed_user.hashed_password
  end

  test "authentication is required even when no one is followed" do
    assert {:error, %Ash.Error.Invalid{errors: errors}} =
             Food.list_followed_users_photos(page: [limit: 12])

    assert Enum.any?(errors, &match?(%Ash.Error.Query.ReadActionRequiresActor{}, &1))
    assert Food.list_followed_users_photos!(actor: user(), page: [limit: 12]).results == []
  end

  test "keyset pages have a stable order for tied upload times" do
    viewer = user()
    followed_user = user()
    Accounts.follow_user!(followed_user.id, actor: viewer)
    file = upload()
    timestamp = DateTime.utc_now()

    photos =
      for _ <- 1..5 do
        create_unanalyzed_photo(followed_user, file)
        |> Ash.Seed.update!(%{inserted_at: timestamp})
      end

    expected_ids = photos |> Enum.map(& &1.id) |> Enum.sort(:desc)
    first = Food.list_followed_users_photos!(actor: viewer, page: [limit: 2])
    assert first.more?
    assert Enum.map(first.results, & &1.id) == Enum.take(expected_ids, 2)

    after_key = List.last(first.results).__metadata__.keyset
    second = Food.list_followed_users_photos!(actor: viewer, page: [limit: 2, after: after_key])
    assert second.more?
    assert Enum.map(second.results, & &1.id) == Enum.slice(expected_ids, 2, 2)

    after_key = List.last(second.results).__metadata__.keyset
    last = Food.list_followed_users_photos!(actor: viewer, page: [limit: 2, after: after_key])
    refute last.more?
    assert Enum.map(last.results, & &1.id) == Enum.drop(expected_ids, 4)
  end
end
