defmodule OpenTrack.Repo.Migrations.AddUserFollows do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:follows, primary_key: false) do
      add :followed_id,
          references(:users,
            column: :id,
            name: "follows_followed_id_fkey",
            type: :uuid,
            on_delete: :delete_all
          ),
          null: false

      add :follower_id,
          references(:users,
            column: :id,
            name: "follows_follower_id_fkey",
            type: :uuid,
            on_delete: :delete_all
          ),
          null: false

      add :id, :uuid, null: false, primary_key: true
    end

    create index(:follows, ["followed_id"])

    create unique_index(:follows, [:follower_id, :followed_id],
             name: "follows_unique_follow_index"
           )
  end

  def down do
    drop_if_exists unique_index(:follows, [:follower_id, :followed_id],
                     name: "follows_unique_follow_index"
                   )

    drop_if_exists index(:follows, ["followed_id"], name: "follows_followed_id_index")

    drop table(:follows)
  end
end
