defmodule OpenTrack.Repo.Migrations.InitCodebase do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:users, primary_key: false) do
      add :hashed_password, :text, null: false
      add :email, :citext, null: false
      add :nickname, :citext, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create unique_index(:users, [:email], name: "users_unique_email_index")
    create unique_index(:users, [:nickname], name: "users_unique_nickname_index")

    create table(:user_attachments, primary_key: false) do
      add :blob_id,
          references(:blobs, column: :id, name: "user_attachments_blob_id_fkey", type: :uuid),
          null: false

      add :name, :text, null: false
      add :inserted_at, :utc_datetime_usec, null: false

      add :user_id,
          references(:users, column: :id, name: "user_attachments_user_id_fkey", type: :uuid),
          null: false

      add :id, :uuid, null: false, primary_key: true
    end

    create table(:tokens, primary_key: false) do
      add :updated_at, :utc_datetime_usec, null: false
      add :created_at, :utc_datetime_usec, null: false
      add :extra_data, :map
      add :purpose, :text, null: false
      add :expires_at, :utc_datetime, null: false
      add :subject, :text, null: false
      add :jti, :text, null: false, primary_key: true
    end

    create table(:settings, primary_key: false) do
      add :user_id, references(:users, column: :id, name: "settings_user_id_fkey", type: :uuid),
        null: false

      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :target_body_fat_percent, :float
      add :target_weight_kg, :float
      add :id, :uuid, null: false, primary_key: true
    end

    create unique_index(:settings, [:user_id], name: "settings_unique_user_index")

    create table(:food_photos, primary_key: false) do
      add :user_id,
          references(:users, column: :id, name: "food_photos_user_id_fkey", type: :uuid),
          null: false

      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :analysis, :map
      add :analysis_status, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create index(:food_photos, ["user_id", "inserted_at"])

    create table(:food_photo_attachments, primary_key: false) do
      add :blob_id,
          references(:blobs,
            column: :id,
            name: "food_photo_attachments_blob_id_fkey",
            type: :uuid
          ),
          null: false

      add :name, :text, null: false
      add :inserted_at, :utc_datetime_usec, null: false

      add :food_photo_id,
          references(:food_photos,
            column: :id,
            name: "food_photo_attachments_food_photo_id_fkey",
            type: :uuid,
            on_delete: :nilify_all
          )

      add :id, :uuid, null: false, primary_key: true
    end

    create table(:blobs, primary_key: false) do
      add :variant_digest, :text
      add :variant_name, :text

      add :variant_of_blob_id,
          references(:blobs, column: :id, name: "blobs_variant_of_blob_id_fkey", type: :uuid)

      add :pending_variants, :boolean, null: false
      add :pending_analyzers, :boolean, null: false
      add :pending_purge, :boolean, null: false
      add :analyzers, :map, default: %{}
      add :metadata, :map, default: %{}
      add :service_opts, :map, default: %{}
      add :service_name, :text, null: false
      add :checksum, :text
      add :byte_size, :bigint
      add :content_type, :text
      add :filename, :text, null: false
      add :key, :text, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create unique_index(:user_attachments, [:user_id, :name],
             name: "user_attachments_unique_user_attachment_index"
           )

    create unique_index(:food_photo_attachments, [:food_photo_id, :name],
             name: "food_photo_attachments_unique_food_photo_attachment_index"
           )

    create unique_index(:blobs, [:key], name: "blobs_unique_key_index")
  end

  def down do
    drop_if_exists unique_index(:blobs, [:key], name: "blobs_unique_key_index")

    drop_if_exists unique_index(:food_photo_attachments, [:food_photo_id, :name],
                     name: "food_photo_attachments_unique_food_photo_attachment_index"
                   )

    drop_if_exists unique_index(:user_attachments, [:user_id, :name],
                     name: "user_attachments_unique_user_attachment_index"
                   )

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `blobs` table without the `blobs_variant_of_blob_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    drop table(:blobs)

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `food_photo_attachments` table without the `food_photo_attachments_food_photo_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `food_photo_attachments` table without the `food_photo_attachments_blob_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    drop table(:food_photo_attachments)

    drop_if_exists index(:food_photos, ["user_id", "inserted_at"],
                     name: "food_photos_user_id_inserted_at_index"
                   )

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `food_photos` table without the `food_photos_user_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    drop table(:food_photos)

    drop_if_exists unique_index(:settings, [:user_id], name: "settings_unique_user_index")

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `settings` table without the `settings_user_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    drop table(:settings)

    drop table(:tokens)

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `user_attachments` table without the `user_attachments_user_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `user_attachments` table without the `user_attachments_blob_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    drop table(:user_attachments)

    drop_if_exists unique_index(:users, [:nickname], name: "users_unique_nickname_index")
    drop_if_exists unique_index(:users, [:email], name: "users_unique_email_index")

    drop table(:users)
  end
end
