defmodule OpenTrack.Repo.Migrations.AddTimezoneToUser do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:settings) do
      add :timezone, :text, null: false, default: "Etc/UTC"
    end
  end

  def down do
    alter table(:settings) do
      remove :timezone
    end
  end
end
